# Generated by Django 4.1.7 on 2023-04-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70)),
                ('Author', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=700)),
                ('Date', models.DateField()),
            ],
        ),
    ]
