# Generated by Django 4.1.7 on 2023-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Post',
            field=models.CharField(max_length=7000),
        ),
    ]
